# Generated by Django 6.0.2 on 2026-02-24 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text='Nama nada bel', max_length=100)),
                ('file', models.FileField(help_text='File audio (mp3/wav)', upload_to='musik/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Musik',
                'verbose_name_plural': 'Musik',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='JadwalBel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text='Keterangan jadwal, misal: Masuk Pagi', max_length=100)),
                ('hari', models.CharField(choices=[('senin', 'Senin'), ('selasa', 'Selasa'), ('rabu', 'Rabu'), ('kamis', 'Kamis'), ('jumat', 'Jumat'), ('sabtu', 'Sabtu'), ('minggu', 'Minggu')], max_length=10)),
                ('jam', models.TimeField(help_text='Waktu bel berbunyi')),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('musik', models.ForeignKey(blank=True, help_text='Nada bel yang diputar', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.musik')),
            ],
            options={
                'verbose_name': 'Jadwal Bel',
                'verbose_name_plural': 'Jadwal Bel',
                'ordering': ['hari', 'jam'],
            },
        ),
    ]
