# Generated by Django 6.0.2 on 2026-02-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musik',
            name='durasi',
            field=models.FloatField(default=0, help_text='Durasi audio dalam detik (otomatis dihitung)'),
        ),
    ]
