# Generated by Django 6.0.2 on 2026-02-25 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_musik_durasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengecualian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(help_text='Tanggal pengecualian')),
                ('alasan', models.CharField(blank=True, default='', help_text='Alasan pengecualian, misal: Libur Nasional, Ujian', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jadwal', models.ForeignKey(help_text='Jadwal bel yang tidak aktif pada tanggal ini', on_delete=django.db.models.deletion.CASCADE, related_name='pengecualian', to='dashboard.jadwalbel')),
            ],
            options={
                'verbose_name': 'Pengecualian',
                'verbose_name_plural': 'Pengecualian',
                'ordering': ['-tanggal', 'jadwal__jam'],
                'unique_together': {('tanggal', 'jadwal')},
            },
        ),
    ]
