# Generated by Django 6.0.2 on 2026-02-27 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Pertanyaan keamanan untuk pemulihan password', max_length=255)),
                ('answer_hash', models.CharField(help_text='Jawaban keamanan (tersimpan dalam bentuk hash)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_question', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pertanyaan Keamanan',
                'verbose_name_plural': 'Pertanyaan Keamanan',
            },
        ),
    ]
